### ISSUE TITLE
Why not use the original finetuned results of base RoBERTa

### ISSUE THREAD

**Issue by BaohaoLiao** [benzakenelad/BitFit#2]
Hi,

In Table 2 of your paper, it seems you reproduce the RoBERTa_base results. May I ask why? Since the RoBERTa paper already released the results. Your reproduced results are worse than the original ones except for task MRPC.

In addition, it seems your hyperparameter setting of reproduction is not the same as in https://github.com/facebookresearch/fairseq/tree/main/examples/roberta/config/finetuning.

**Comment by benzakenelad** [comment]
Thanks for reaching out @BaohaoLiao, the reason is to align the experiments in our work with what Adapter and Diff-Pruning did.
Regarding the hyperparameters, you are right they are not identical to what RoBERTa authors did. With that, BitFit paper delivers an idea for parameter efficient fine-tuning (it's not SOTA in a task work) so we didn't spend too much time on hyperparameters optimization, etc.
